library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("syuzhet")
library("ggplot2")
library("tm")
library("RSQLite")
library("quanteda")
rm(list=ls())
comments <- read.csv("Womens Clothing E-Commerce Reviews.csv", na.strings = "No comment!")
higher_rate <-comments[comments$Rating >= 3, ] 
higher_rate_titiles <-higher_rate[,4] 
docs <- Corpus(VectorSource(higher_rate_titiles))
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, stemDocument)
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
par(bg="grey30")
png(file="WordCloud.png",width=1000,height=700, bg="grey30")
wordcloud(d$word, d$freq, col=terrain.colors(length(d$word), alpha=0.9), random.order=FALSE, rot.per=0.3 )
title(main = "Top Comments", font.main = 3, col.main = "cornsilk3", cex.main = 1.5)
dev.off()

